In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
##  create a dataframe
df = pd.read_csv("base_modelagem.csv", sep=";")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 511721 entries, 0 to 511720
Data columns (total 12 columns):
PAGTO                         511721 non-null int64
GRP_PRAZO_ULTIMACOMPRA_03M    511721 non-null object
GRP_QTDE_COMPRAS_ULT03M       511721 non-null object
GRP_QTDE_COMPULT03M_OFFUS     511721 non-null object
GRP_TMP_FAT_ANTERIOR_M1       511721 non-null object
GRP_QTD_SLDOCRESC_06M         511721 non-null object
GRP_FATURAATUALSLDTOTAL_M0    511721 non-null object
GRP_FATURAATUALFATAVG_3M      511721 non-null object
GRP_QTD_PGTOMENOSMIN_03M      511721 non-null object
GRP_QTD_ROTATIVOU_12M         511721 non-null object
GRP_QTD_FATURAS_06M           511721 non-null object
GRP_QTDE_ITENS_ULT01M_OPT     511721 non-null object
dtypes: int64(1), object(11)
memory usage: 46.8+ MB

In [78]:
df2=pd.get_dummies(df, prefix=['col1', 'col2', 'col3','col4','col5','col6', 'col7','col8','col9','col10','col11'])

In [79]:
df2.head(5)

,PAGTO,"col1_(-Inf,2]","col1_(2,3]","col1_(3,7]","col1_(7, Inf]",col1_Missing,"col2_(-Inf,1]","col2_(1, Inf]",col2_Missing,"col3_(-Inf,4]",...,"col9_(1,2]","col9_(2, Inf]",col9_Missing,"col10_(-Inf,3]","col10_(3,4]","col10_(4, Inf]",col10_Missing,"col11_(-Inf,1]","col11_(1, Inf]",col11_Missing
0,0,0,0,0,0,1,0,0,1,0,...,0,0,0,1,0,0,0,0,0,1
1,1,0,0,0,0,1,0,0,1,0,...,0,0,0,0,1,0,0,0,0,1
2,0,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,1
3,0,0,0,0,0,1,0,0,1,1,...,0,0,0,0,1,0,0,0,0,1
4,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,0,1,0,0,0,1

In [82]:
df2=df2.rename({'col1_(-Inf,2]':'col1_a',	'col1_(2,3]':'col1_b',	'col1_(3,7]':'col1_c',	'col1_(7, Inf]':'col1_d',	'col1_Missing':'col1_e',	'col2_(-Inf,1]':'col2_a',	'col2_(1, Inf]':'col2_b',	'col2_Missing':'col2_c',	'col3_(-Inf,4]':'col3_a',	'col3_(15, Inf]':'col3_b',	'col3_(4,9]':'col3_c',	'col3_(9,15]':'col3_d',	'col3_Missing':'col3_e',	'col4_(-Inf,2]':'col4_a',	'col4_(2, Inf]':'col4_b',	'col4_Missing':'col4_c',	'col5_(-Inf,0]':'col5_a',	'col5_(0,1]':'col5_b',	'col5_(1,2]':'col5_c',	'col5_(2, Inf]':'col5_d',	'col5_Missing':'col5_e',	'col6_(-Inf,0.4232]':'col6_a',	'col6_(0.4232,0.4995]':'col6_b',	'col6_(0.4995, Inf]':'col6_c',	'col6_Missing':'col6_d',	'col7_(-Inf,0.1996]':'col7_a',	'col7_(0.1996,1.1464]':'col7_b',	'col7_(1.1464,1.2778]':'col7_c',	'col7_(1.2778,1.5056]':'col7_d',	'col7_(1.5056, Inf]':'col7_e',	'col7_Missing':'col7_f',	'col8_(-Inf,1]':'col8_a',	'col8_(1, Inf]':'col8_b',	'col8_Missing':'col8_c',	'col9_(-Inf,0]':'col9_a',	'col9_(0,1]':'col9_b',	'col9_(1,2]':'col9_c',	'col9_(2, Inf]':'col9_d',	'col9_Missing':'col9_e',	'col10_(-Inf,3]':'col1_a',	'col10_(3,4]':'col1_b',	'col10_(4, Inf]':'col1_c',	'col10_Missing':'col1_d',	'col11_(-Inf,1]':'col11_a',	'col11_(1, Inf]':'col11_b',	'col11_Missing':'col11_c'}, axis='columns')

In [83]:
df2.isnull().sum()

PAGTO      0
col1_a     0
col1_b     0
col1_c     0
col1_d     0
col1_e     0
col2_a     0
col2_b     0
col2_c     0
col3_a     0
col3_b     0
col3_c     0
col3_d     0
col3_e     0
col4_a     0
col4_b     0
col4_c     0
col5_a     0
col5_b     0
col5_c     0
col5_d     0
col5_e     0
col6_a     0
col6_b     0
col6_c     0
col6_d     0
col7_a     0
col7_b     0
col7_c     0
col7_d     0
col7_e     0
col7_f     0
col8_a     0
col8_b     0
col8_c     0
col9_a     0
col9_b     0
col9_c     0
col9_d     0
col9_e     0
col1_a     0
col1_b     0
col1_c     0
col1_d     0
col11_a    0
col11_b    0
col11_c    0
dtype: int64

In [48]:
import statsmodels.formula.api as smf
import statsmodels.api as sm

In [84]:
formula = 'PAGTO ~ col1_a+	col1_b+	col1_c+	col1_d+	col1_e+	col2_a+	col2_b+	col2_c+	col3_a+	col3_b+	col3_c+	col3_d+	col3_e+	col4_a+	col4_b+	col4_c+	col5_a+	col5_b+	col5_c+	col5_d+	col5_e+	col6_a+	col6_b+	col6_c+	col6_d+	col7_a+	col7_b+	col7_c+	col7_d+	col7_e+	col7_f+	col8_a+	col8_b+	col8_c+	col9_a+	col9_b+	col9_c+	col9_d+	col9_e+	col1_a+	col1_b+	col1_c+	col1_d+	col11_a+	col11_b+	col11_c'

In [85]:
model = smf.glm(formula = formula, data=df2, family=sm.families.Binomial())
result = model.fit()
print(result.summary())

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\family.py:879: RuntimeWarning: invalid value encountered in true_divide
  endog_mu = self._clean(endog / mu)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\family.py:881: RuntimeWarning: invalid value encountered in log
  resid_dev = endog * np.log(endog_mu) + (1 - endog) * np.log(n_endog_mu)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\family.py:880: RuntimeWarning: divide by zero encountered in true_divide
  n_endog_mu = self._clean((1. - endog) / (1. - mu))
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\family.py:880: RuntimeWarning: invalid value encountered in true_divide
  n_endog_mu = self._clean((1. - endog) / (1. - mu))
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\family.py:879: RuntimeWarning: divide by zero encountered in true_divide
  endog_mu = self._clean(endog / mu)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\family.py:932: RuntimeWarning: divide by zero encountered in true_divide
  special.gammaln(n - y + 1) + y * np.log(mu / (1 - mu)) +
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\family.py:932: RuntimeWarning: divide by zero encountered in log
  special.gammaln(n - y + 1) + y * np.log(mu / (1 - mu)) +
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\family.py:932: RuntimeWarning: invalid value encountered in multiply
  special.gammaln(n - y + 1) + y * np.log(mu / (1 - mu)) +
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\family.py:933: RuntimeWarning: divide by zero encountered in log
  n * np.log(1 - mu)) * var_weights
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\family.py:933: RuntimeWarning: invalid value encountered in add
  n * np.log(1 - mu)) * var_weights

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                  PAGTO   No. Observations:               511721
Model:                            GLM   Df Residuals:                   511687
Model Family:                Binomial   Df Model:                           33
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                    nan
Date:                Thu, 30 Jan 2020   Deviance:                          nan
Time:                        18:34:40   Pearson chi2:                 3.79e+20
No. Iterations:                   100   Covariance Type:             nonrobust
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -2.647e+25   1.67e+18  -1.59e+07      0.000   -2.65e+25   -2.65e+25
col1_a[0]  -3.996e+24   1.74e+17  -2.29e+07      0.000      -4e+24      -4e+24
col1_a[1]   2.023e+25   3.25e+17   6.23e+07      0.000    2.02e+25    2.02e+25
col1_b[0]  -3.996e+24   1.74e+17  -2.29e+07      0.000      -4e+24      -4e+24
col1_b[1]   2.023e+25   3.25e+17   6.23e+07      0.000    2.02e+25    2.02e+25
col1_c[0]  -3.996e+24   1.74e+17  -2.29e+07      0.000      -4e+24      -4e+24
col1_c[1]   2.023e+25   3.25e+17   6.23e+07      0.000    2.02e+25    2.02e+25
col1_d[0]  -3.996e+24   1.74e+17  -2.29e+07      0.000      -4e+24      -4e+24
col1_d[1]   1.003e+25    3.6e+17   2.78e+07      0.000       1e+25       1e+25
col1_e      3.595e+25   5.23e+18   6.87e+06      0.000     3.6e+25     3.6e+25
col2_a       7.61e+25   1.05e+19   7.26e+06      0.000    7.61e+25    7.61e+25
col2_b       7.61e+25   1.05e+19   7.26e+06      0.000    7.61e+25    7.61e+25
col2_c      3.615e+25   5.25e+18   6.89e+06      0.000    3.61e+25    3.61e+25
col3_a      6.236e+23   3.27e+17   1.91e+06      0.000    6.24e+23    6.24e+23
col3_b      6.236e+23   3.27e+17   1.91e+06      0.000    6.24e+23    6.24e+23
col3_c      6.236e+23   3.27e+17   1.91e+06      0.000    6.24e+23    6.24e+23
col3_d      6.236e+23   3.27e+17   1.91e+06      0.000    6.24e+23    6.24e+23
col3_e      6.236e+23   3.27e+17   1.91e+06      0.000    6.24e+23    6.24e+23
col4_a     -2.932e+25   3.48e+17  -8.44e+07      0.000   -2.93e+25   -2.93e+25
col4_b     -2.932e+25   3.48e+17  -8.44e+07      0.000   -2.93e+25   -2.93e+25
col4_c     -2.932e+25   3.48e+17  -8.44e+07      0.000   -2.93e+25   -2.93e+25
col5_a     -3.803e+23   6.46e+17  -5.88e+05      0.000    -3.8e+23    -3.8e+23
col5_b     -3.803e+23   6.46e+17  -5.88e+05      0.000    -3.8e+23    -3.8e+23
col5_c     -3.803e+23   6.46e+17  -5.88e+05      0.000    -3.8e+23    -3.8e+23
col5_d     -3.803e+23   6.46e+17  -5.88e+05      0.000    -3.8e+23    -3.8e+23
col5_e      9.822e+24   3.64e+17    2.7e+07      0.000    9.82e+24    9.82e+24
col6_a     -1.292e+24   3.06e+17  -4.22e+06      0.000   -1.29e+24   -1.29e+24
col6_b     -1.292e+24   3.06e+17  -4.22e+06      0.000   -1.29e+24   -1.29e+24
col6_c     -1.292e+24   3.06e+17  -4.22e+06      0.000   -1.29e+24   -1.29e+24
col6_d     -1.292e+24   3.06e+17  -4.22e+06      0.000   -1.29e+24   -1.29e+24
col7_a     -4.725e+24    6.5e+17  -7.27e+06      0.000   -4.72e+24   -4.72e+24
col7_b     -4.725e+24    6.5e+17  -7.27e+06      0.000   -4.72e+24   -4.72e+24
col7_c     -4.725e+24    6.5e+17  -7.27e+06      0.000   -4.72e+24   -4.72e+24
col7_d     -4.725e+24    6.5e+17  -7.27e+06      0.000   -4.72e+24   -4.72e+24
col7_e     -4.725e+24    6.5e+17  -7.27e+06      0.000   -4.72e+24   -4.72e+24
col7_f     -4.725e+24    6.5e+17  -7.27e+06      0.000   -4.72e+24   -4.72e+24
col8_a     -1.034e+25   2.84e+18  -3.65e+06      0.000   -1.03e+25   -1.03e+25
col8_b     -1.034e+25   2.84e+18  -3.65e+06      0.000   -1.03e+25   -1.03e+25
col8_c     -1.034e+25   2.84e+18  -3.65e+06      0.000   -1.03e+25   -1.03e+25
col9_a     -6.859e+23   3.85e+18  -1.78e+05      0.000   -6.86e+23   -6.86e+23
col9_b     -6.859e+23   3.85e+18  -1.78e+05      0.000   -6.86e+23   -6.86e+23
col9_c     -6.859e+23   3.85e+18  -1.78e+05      0.000   -6.86e+23   -6.86e+23
col9_d     -6.859e+23   3.85e+18  -1.78e+05      0.000   -6.86e+23   -6.86e+23
col9_e     -6.859e+23   3.85e+18  -1.78e+05      0.000   -6.86e+23   -6.86e+23
col11_a    -1.974e+25   9.01e+18  -2.19e+06      0.000   -1.97e+25   -1.97e+25
col11_b    -1.974e+25   9.01e+18  -2.19e+06      0.000   -1.97e+25   -1.97e+25
col11_c    -1.974e+25   9.01e+18  -2.19e+06      0.000   -1.97e+25   -1.97e+25
==============================================================================

In [11]:
from sklearn.model_selection import train_test_split

In [ ]:
Xo_train, Xo_test, yo_train, yo_test = train_test_split(data_o, target_o, test_size=0.20, random_state=4)