# Atividade de Pandas -
#### Conteúdos: 
- Seleção de Dados


use o dataset: **COVID19 cases Toronto.csv**

In [1]:
import pandas as pd

In [2]:
filename = '../data/COVID19 cases Toronto.csv'
df = pd.read_csv(filename)

**1. Apresente uma função que irá retornar 10% de registros aleatórios do dataset COVID19 cases Toronto.csv**

In [3]:
df.sample(frac=0.1)

,_id,Outbreak Associated,Age Group,Neighbourhood Name,FSA,Source of Infection,Classification,Episode Date,Reported Date,Client Gender,Outcome,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated
6529,50823,Outbreak Associated,50-59,Old East York,M4J,N/A - Outbreak associated,CONFIRMED,2020-04-14,2020-04-16,FEMALE,RESOLVED,No,No,No,No,No,No
2378,46672,Sporadic,30-39,Wexford/Maryvale,M1R,Close contact,PROBABLE,2020-03-31,2020-04-04,MALE,RESOLVED,No,No,No,No,No,No
836,45130,Sporadic,20-29,Morningside,M1E,Close contact,CONFIRMED,2020-05-31,2020-06-03,FEMALE,RESOLVED,No,No,No,No,No,No
3598,47892,Outbreak Associated,40-49,Willowdale West,M2N,N/A - Outbreak associated,CONFIRMED,2020-04-15,2020-04-16,FEMALE,RESOLVED,No,No,No,No,No,No
11488,55782,Sporadic,30-39,Princess-Rosethorn,M9B,Close contact,CONFIRMED,2020-04-22,2020-04-23,MALE,RESOLVED,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7622,51916,Outbreak Associated,50-59,Church-Yonge Corridor,M5B,N/A - Outbreak associated,CONFIRMED,2020-04-16,2020-04-18,FEMALE,RESOLVED,No,No,No,No,No,No
10575,54869,Outbreak Associated,70-79,Runnymede-Bloor West Village,M6S,N/A - Outbreak associated,CONFIRMED,2020-03-31,2020-04-04,MALE,RESOLVED,No,No,No,Yes,No,No
1891,46185,Sporadic,19 and younger,Scarborough Village,M1M,Close contact,CONFIRMED,2020-05-21,2020-05-28,MALE,RESOLVED,No,No,No,No,No,No
4437,48731,Sporadic,40-49,York University Heights,M3J,Institutional,CONFIRMED,2020-04-22,2020-04-24,FEMALE,RESOLVED,No,No,No,No,No,No
10444,54738,Sporadic,40-49,High Park North,M6P,Community,CONFIRMED,2020-03-09,2020-03-23,FEMALE,RESOLVED,No,No,No,No,No,No

**2. Apresente uma função que irá retornar os dados entre o índice 100 e 120 das colunas Classification e Age Group**

In [4]:
df.loc[100:120, ['Classification', 'Age Group']]

    Classification       Age Group
100      CONFIRMED           60-69
101      CONFIRMED           50-59
102      CONFIRMED           60-69
103      CONFIRMED           60-69
104      CONFIRMED           40-49
105      CONFIRMED           40-49
106      CONFIRMED           70-79
107      CONFIRMED           50-59
108      CONFIRMED           20-29
109      CONFIRMED           60-69
110      CONFIRMED           60-69
111      CONFIRMED           60-69
112      CONFIRMED           50-59
113      CONFIRMED           30-39
114      CONFIRMED           30-39
115       PROBABLE           60-69
116      CONFIRMED           30-39
117       PROBABLE  19 and younger
118       PROBABLE  19 and younger
119       PROBABLE           50-59
120      CONFIRMED           30-39

**3. Apresente uma função que irá retornar os dados que estão entre a posições 50 e 70 das colunas últimas seis colunas do dataset**

In [5]:
df.iloc[50:70, -6:]

,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated
50,No,No,No,No,No,No
51,No,No,No,No,No,No
52,No,No,No,No,No,No
53,No,No,No,No,No,No
54,No,No,No,No,No,No
55,No,No,No,Yes,No,No
56,No,No,No,No,No,No
57,No,No,No,No,No,No
58,No,No,No,No,No,No
59,No,No,No,Yes,No,No
60,No,No,No,No,No,No
61,No,No,No,No,No,No
62,No,No,No,No,No,No
63,No,No,No,No,No,No
64,No,No,No,No,No,No
65,No,No,No,No,No,No
66,No,No,No,No,No,No
67,No,No,No,No,No,No
68,No,No,No,No,No,No
69,No,No,No,No,No,No

**4. Apresente um código pandas que retornará os registros que tem idade entre 50 e 59 anos que tiveram casos confirmados**

In [6]:
df

,_id,Outbreak Associated,Age Group,Neighbourhood Name,FSA,Source of Infection,Classification,Episode Date,Reported Date,Client Gender,Outcome,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated
0,44294,Sporadic,50-59,Malvern,M1B,Institutional,CONFIRMED,2020-03-25,2020-03-27,MALE,RESOLVED,No,No,No,No,No,No
1,44295,Sporadic,20-29,Malvern,M1B,Community,CONFIRMED,2020-03-20,2020-03-28,MALE,RESOLVED,No,No,No,Yes,No,No
2,44296,Sporadic,60-69,Malvern,M1B,Travel,CONFIRMED,2020-03-04,2020-03-08,FEMALE,RESOLVED,No,No,No,Yes,Yes,Yes
3,44297,Outbreak Associated,50-59,Rouge,M1B,N/A - Outbreak associated,CONFIRMED,2020-05-02,2020-05-04,FEMALE,RESOLVED,No,No,No,No,No,No
4,44298,Sporadic,30-39,Rouge,M1B,Close contact,CONFIRMED,2020-05-31,2020-06-06,FEMALE,RESOLVED,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14906,59200,Outbreak Associated,50-59,NaN,NaN,N/A - Outbreak associated,CONFIRMED,2020-06-11,2020-06-15,FEMALE,RESOLVED,No,No,No,No,No,No
14907,59201,Outbreak Associated,20-29,NaN,NaN,N/A - Outbreak associated,CONFIRMED,2020-05-09,2020-05-23,FEMALE,RESOLVED,No,No,No,No,No,No
14908,59202,Outbreak Associated,40-49,NaN,NaN,N/A - Outbreak associated,CONFIRMED,2020-06-18,2020-06-19,FEMALE,RESOLVED,No,No,No,No,No,No
14909,59203,Outbreak Associated,19 and younger,NaN,NaN,N/A - Outbreak associated,PROBABLE,2020-06-13,2020-06-13,MALE,RESOLVED,No,No,No,No,No,No
14910,59204,Outbreak Associated,50-59,NaN,NaN,N/A - Outbreak associated,CONFIRMED,2020-06-22,2020-06-23,FEMALE,RESOLVED,No,No,No,Yes,No,No

In [7]:
df[(df['Age Group'] == '50-59') & (df['Classification']=='CONFIRMED')]

,_id,Outbreak Associated,Age Group,Neighbourhood Name,FSA,Source of Infection,Classification,Episode Date,Reported Date,Client Gender,Outcome,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated
0,44294,Sporadic,50-59,Malvern,M1B,Institutional,CONFIRMED,2020-03-25,2020-03-27,MALE,RESOLVED,No,No,No,No,No,No
3,44297,Outbreak Associated,50-59,Rouge,M1B,N/A - Outbreak associated,CONFIRMED,2020-05-02,2020-05-04,FEMALE,RESOLVED,No,No,No,No,No,No
16,44310,Sporadic,50-59,Malvern,M1B,Institutional,CONFIRMED,2020-04-13,2020-04-15,FEMALE,RESOLVED,No,No,No,No,No,No
21,44315,Sporadic,50-59,Malvern,M1B,Close contact,CONFIRMED,2020-04-25,2020-05-01,FEMALE,RESOLVED,No,No,No,No,No,No
22,44316,Sporadic,50-59,Malvern,M1B,Close contact,CONFIRMED,2020-05-01,2020-05-07,MALE,RESOLVED,No,No,No,Yes,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14892,59186,Outbreak Associated,50-59,NaN,NaN,N/A - Outbreak associated,CONFIRMED,2020-05-23,2020-05-25,MALE,RESOLVED,No,No,No,No,No,No
14901,59195,Outbreak Associated,50-59,NaN,NaN,N/A - Outbreak associated,CONFIRMED,2020-05-24,2020-05-25,MALE,RESOLVED,No,No,No,No,No,No
14905,59199,Outbreak Associated,50-59,NaN,NaN,N/A - Outbreak associated,CONFIRMED,2020-06-02,2020-06-03,FEMALE,RESOLVED,No,No,No,No,No,No
14906,59200,Outbreak Associated,50-59,NaN,NaN,N/A - Outbreak associated,CONFIRMED,2020-06-11,2020-06-15,FEMALE,RESOLVED,No,No,No,No,No,No
14910,59204,Outbreak Associated,50-59,NaN,NaN,N/A - Outbreak associated,CONFIRMED,2020-06-22,2020-06-23,FEMALE,RESOLVED,No,No,No,Yes,No,No

**5. Apresente um código pandas que retornará os registros dos seguintes bairros ['Malvern', 'Rouge', 'Thorncliffe Park', 'Bendale']**

In [ ]:
df[df['Neighbourhood Name'].isin(['Malvern', 'Rouge', 'Thorncliffe Park', 'Bendale'])]